version: '3'
services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_URL=jdbc:postgresql://db:5432/postgres
      - DB_USERNAME=username
      - DB_PASSWORD=password
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=bitespeed
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
